module.exports = {
    admin: require('./adminModel'),
    user: require('./userModel'),
    otp: require('./otpModel'),
    business: require('./businessModel'),
    businessDocs: require('./businessDocsModel'),
    businessCategory: require('./businessCategoryModel'),
    membership: require('./MembershipModel'),
    membership_package: require('./membershipPackageModel'),
    countries: require('./countryModel'),
    city: require('./cityModel'),
    state: require('./stateModel'),
    postalcode: require('./postalCodeModel'),
    events: require('./eventModel'),
    tokens: require('./tokenModel'),
    chapter: require('./chapterModel'),
    partnerRequest: require('./partnerRequestModel'),
    role: require('./roleModel'),
    wallet: require('./walletModel'),
    range: require('./turnoverRangeModel'),
    modules: require('./modulesModel'),
    payment: require('./paymentModel'),
    blog: require('../model/blogModel'),
    transaction: require('../model/transactionModel'),
  };
  